owner: schematixinc
repo: status

sites:
  - name: Relay API
    url: https://api.relay.us/health
    expectedStatusCodes: [200]
  - name: Relay App
    url: https://relay.us
    expectedStatusCodes: [200]

status-website:
  name: Relay Status
  url: https://status.relay.us
  cname: status.relay.us

notifications:
  - type: slack
    channel: "#relay-alerts"
